language: perl
# v0.003_000

# NEED FIX, CORRELATION #ap010: old version of Travis build OS does not support apt-get installation of libtexinfo* ???
#addons:
#    apt:
#        packages:
#            - libtexinfo
#            - libtexinfo-dev

perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
#    - "5.25"  # built using Travis-CI Helper; NEED ANSWER, NO LONGER AVAILABLE???
    - "5.26"
#    - "5.27"  # built using Travis-CI Helper; NEED ANSWER, NO LONGER AVAILABLE???
#    - "dev"  # built using Travis-CI Helper, same as latest 5.odd dev version above
    - "blead"  # built using Travis-CI Helper

# [ BEGIN Travis-CI Helper ]
matrix:
    allow_failures:
        - perl: "blead"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V

# NEED UPGRADE: use build-dist instead of cpanm calls below?
#    - build-dist
#    - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
# [ END Travis-CI Helper ]

install:
    - cpanm --verbose --installdeps .

script:
    - perl Makefile.PL
    - make
    - make test
    - make install
    - perl -e 'use Alien::Texinfo; use Env qw(@PATH); unshift @PATH, Alien::Texinfo->bin_dir(); print `which makeinfo`, `makeinfo --version`, "\n";'

notifications:
  irc:
    channels:
        - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
        - "Alien::Texinfo build %{result}. %{author} says '%{commit_message}'"
        - "%{build_url} %{compare_url}"

env:
    global:
        - AUTHOR_TESTING=0
#    matrix:
#        - ALIEN_INSTALL_TYPE=share
# NEED FIX, CORRELATION #ap010: old version of Travis build OS does not support apt-get installation of libtexinfo* ???
#        - ALIEN_INSTALL_TYPE=system
